/* Writes one account's lists, as they are now in the database (DATABASE_URL), as a SQL file that
 * gives them to another username: e.g. to copy everything to your account on Hostinger.
 *
 *   npm run db:export -- --from antoine@example.com --to grollian
 *                       → db/grollian.sql (import it in phpMyAdmin, after db/schema.sql)
 *
 * --from: email or username of the account to copy (default: the "default" user).
 * --to:   username that gets the lists. The account must exist where you import the file; its
 *         characters, components and words are replaced.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import mysql from 'mysql2/promise';
import { normalizeEmail, normalizeUsername, usernameError } from '../src/app/core/auth.model.ts';
import { ROOT } from '../server/data-files.ts';
import { createStores } from '../server/store.ts';
import { seedSql } from './seed-sql.ts';

const args = process.argv.slice(2);
const option = (name: string) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const from = option('--from') ?? 'default';
const to = option('--to');
if (!to || usernameError(to)) {
  console.error(`Give the username that gets the lists: --to <username>${to ? ` (${usernameError(to)})` : ''}`);
  process.exit(1);
}
const target = normalizeUsername(to);

const stores = createStores();
try {
  const [[source]] = await stores.pool.query<mysql.RowDataPacket[]>(
    from.includes('@')
      ? `SELECT id, email, username FROM app_user WHERE email = ?`
      : `SELECT id, email, username FROM app_user WHERE username = ?`,
    [from.includes('@') ? normalizeEmail(from) : normalizeUsername(from)],
  );
  if (!source) {
    console.error(`No account "${from}" in ${stores.description}.`);
    process.exitCode = 1;
  } else {
    const characters = await stores.characters.all(source['id']);
    const words = await stores.words.all(source['id']);
    const label = source['username'] ?? source['email'];
    const sql = seedSql(characters, words, {
      username: target,
      title: `Generated by "npm run db:export" from the lists of ${label} (user ${source['id']}), ${new Date().toISOString().slice(0, 10)}.`,
      createUser: false,
    });
    const file = join(ROOT, 'db', `${target}.sql`);
    writeFileSync(file, sql);
    console.log(`Wrote ${file}: ${characters.length} characters and ${words.length} words of ${label} for "${target}".`);
  }
} finally {
  await stores.pool.end();
}
