/* Copies data/characters.json and data/words.json (or DATA_DIR) into PostgreSQL, keeping the order.
 *
 *   npm run db:import -- --sql                 only write db/seed.sql (run it with psql or paste it
 *                                              in your database's SQL editor, after db/schema.sql)
 *   npm run db:import                          create the tables (db/schema.sql) and import into
 *                                              DATABASE_URL
 *   npm run db:import -- --user anna           import as another user (default: "default")
 *   npm run db:import -- --replace             replace that user's lists if they already have data
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';
import { CHARACTERS, ROOT, WORDS, readList } from '../server/data-files.ts';
import { CharacterEntry } from '../src/app/core/character.model.ts';
import {
  CHARACTERS_TABLE,
  WORDS_TABLE,
  componentsOf,
  partOverride,
  userIdOf,
} from '../server/store.ts';

const args = process.argv.slice(2);
const sqlOnly = args.includes('--sql');
const replace = args.includes('--replace');
const userIndex = args.indexOf('--user');
const username = (userIndex >= 0 && args[userIndex + 1]) || 'default';

const quote = (value: unknown): string =>
  value == null ? 'NULL' : `'${String(value).replaceAll("'", "''")}'`;

const user = `(SELECT id FROM app_user WHERE username = ${quote(username)})`;

/** The components and character_components tables, from the characters' components. */
function componentsSql(characters: CharacterEntry[]): string {
  const components = componentsOf(characters);
  const lines = [`DELETE FROM components WHERE user_id = ${user};`];
  if (!components.size) return lines.join('\n');
  lines.push(
    `INSERT INTO components (user_id, hanzi, pinyin, meaning)`,
    `SELECT ${user}, v.* FROM (VALUES`,
    [...components]
      .map(([hanzi, c]) => `  (${quote(hanzi)}, ${quote(c.pinyin)}, ${quote(c.meaning)})`)
      .join(',\n'),
    `) AS v (hanzi, pinyin, meaning);`,
    ``,
    `INSERT INTO character_components (character_id, component_id, position, role, strokes, pinyin, meaning)`,
    `SELECT ch.id, co.id, v.position, v.role, v.strokes, v.pinyin, v.meaning FROM (VALUES`,
    characters
      .flatMap((c) =>
        (c.components ?? []).map((part, i) => {
          const general = components.get(part.character)!;
          const values = [
            c.character,
            i + 1,
            part.character,
            part.role,
            part.strokes,
            partOverride(part.pinyin, general.pinyin),
            partOverride(part.meaning, general.meaning),
          ];
          return `  (${values.map((v) => (typeof v === 'number' ? v : quote(v))).join(', ')})`;
        }),
      )
      .join(',\n'),
    `) AS v (hanzi, position, component, role, strokes, pinyin, meaning)`,
    `JOIN characters ch ON ch.user_id = ${user} AND ch.hanzi = v.hanzi`,
    `JOIN components co ON co.user_id = ${user} AND co.hanzi = v.component;`,
  );
  return lines.join('\n');
}

/** DELETE + INSERT of one user's list, with the JSON array order as position. */
function listSql(table: typeof CHARACTERS_TABLE | typeof WORDS_TABLE, items: unknown[]): string {
  const lines = [`DELETE FROM ${table.name} WHERE user_id = ${user};`];
  if (items.length) {
    const rows = items.map((item, i) => {
      const values = (table.toRow as (x: unknown) => unknown[])(item).map((v, k) => {
        const column = table.columns[k];
        return column === 'words' ? `${quote(v)}::jsonb` : quote(v);
      });
      return `  (${i + 1}, ${values.join(', ')})`;
    });
    lines.push(
      `INSERT INTO ${table.name} (user_id, position, ${table.columns.join(', ')})`,
      `SELECT ${user}, v.* FROM (VALUES`,
      rows.join(',\n'),
      `) AS v (position, ${table.columns.join(', ')});`,
    );
  }
  return lines.join('\n');
}

const characters = await readList(CHARACTERS);
const words = await readList(WORDS);
const seed = [
  `-- Generated by "npm run db:import -- --sql" from your JSON lists. Run db/schema.sql first.`,
  `-- Replaces the lists of user ${quote(username)}.`,
  `SET standard_conforming_strings = on;`,
  `BEGIN;`,
  `INSERT INTO app_user (username) VALUES (${quote(username)}) ON CONFLICT (username) DO NOTHING;`,
  listSql(CHARACTERS_TABLE, characters),
  componentsSql(characters),
  listSql(WORDS_TABLE, words),
  `COMMIT;`,
  ``,
].join('\n\n');

if (sqlOnly) {
  const file = join(ROOT, 'db', 'seed.sql');
  writeFileSync(file, seed);
  console.log(`Wrote ${file}: ${characters.length} characters, ${words.length} words.`);
  process.exit(0);
}

const url = process.env['DATABASE_URL'];
if (!url) {
  console.error('Set DATABASE_URL (or use --sql to only write db/seed.sql).');
  process.exit(1);
}
const client = new pg.Client({ connectionString: url });
await client.connect();
try {
  await client.query(readFileSync(join(ROOT, 'db', 'schema.sql'), 'utf8'));
  const userId = await userIdOf(client, username);
  const { rows } = await client.query(
    `SELECT (SELECT count(*) FROM characters WHERE user_id = $1)
          + (SELECT count(*) FROM words WHERE user_id = $1)
          + (SELECT count(*) FROM components WHERE user_id = $1) AS n`,
    [userId],
  );
  if (Number(rows[0].n) > 0 && !replace) {
    console.error(`User "${username}" already has ${rows[0].n} rows. Use --replace to overwrite them.`);
    process.exitCode = 1;
  } else {
    await client.query(seed);
    console.log(`Imported ${characters.length} characters and ${words.length} words for "${username}".`);
  }
} finally {
  await client.end();
}
