/* Copies data/characters.json and data/words.json (or DATA_DIR) into MySQL / MariaDB, keeping the order.
 *
 *   npm run db:import -- --sql                 only write db/seed.sql (import it in phpMyAdmin, or
 *                                              run it with the mariadb/mysql client, after
 *                                              db/schema.sql)
 *   npm run db:import                          create the tables (db/schema.sql) and import into
 *                                              DATABASE_URL
 *   npm run db:import -- --user anna           import as another user (default: "default")
 *   npm run db:import -- --replace             replace that user's lists if they already have data
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import mysql from 'mysql2/promise';
import { CHARACTERS, ROOT, WORDS, readList } from '../server/data-files.ts';
import { CharacterEntry } from '../src/app/core/character.model.ts';
import {
  CHARACTERS_TABLE,
  WORDS_TABLE,
  componentsOf,
  partOverride,
  userIdOf,
} from '../server/store.ts';

const args = process.argv.slice(2);
const sqlOnly = args.includes('--sql');
const replace = args.includes('--replace');
const userIndex = args.indexOf('--user');
const username = (userIndex >= 0 && args[userIndex + 1]) || 'default';

/** SQL literal (mysql2 escapes quotes and backslashes). */
const quote = (value: unknown): string => (value == null ? 'NULL' : mysql.escape(String(value)));

/** INSERT … VALUES with one line per row, or nothing when there are no rows. */
const insertSql = (table: string, columns: string[], rows: string[][]): string =>
  rows.length
    ? `INSERT INTO ${table} (${columns.join(', ')}) VALUES\n` +
      rows.map((values) => `  (${values.join(', ')})`).join(',\n') +
      ';'
    : '';

/** The user's list, with the JSON array order as position. */
function listSql(table: typeof CHARACTERS_TABLE | typeof WORDS_TABLE, items: unknown[]): string {
  const toRow = table.toRow as (item: unknown) => unknown[];
  return insertSql(
    table.name,
    ['user_id', 'position', ...table.columns],
    items.map((item, i) => ['@user', String(i + 1), ...toRow(item).map(quote)]),
  );
}

/** The components and character_components tables, from the characters' components. */
function componentsSql(characters: CharacterEntry[]): string {
  const components = componentsOf(characters);
  const idOf = (table: string, hanzi: string) =>
    `(SELECT id FROM ${table} WHERE user_id = @user AND hanzi = ${quote(hanzi)})`;
  return [
    insertSql(
      'components',
      ['user_id', 'hanzi', 'pinyin', 'meaning'],
      [...components].map(([hanzi, c]) => ['@user', quote(hanzi), quote(c.pinyin), quote(c.meaning)]),
    ),
    insertSql(
      'character_components',
      ['character_id', 'component_id', 'position', 'role', 'strokes', 'pinyin', 'meaning'],
      characters.flatMap((c) =>
        (c.components ?? []).map((part, i) => {
          const general = components.get(part.character)!;
          return [
            idOf('characters', c.character),
            idOf('components', part.character),
            String(i + 1),
            quote(part.role),
            quote(part.strokes),
            quote(partOverride(part.pinyin, general.pinyin)),
            quote(partOverride(part.meaning, general.meaning)),
          ];
        }),
      ),
    ),
  ].join('\n\n');
}

const characters = await readList(CHARACTERS);
const words = await readList(WORDS);
const seed = [
  `-- Generated by "npm run db:import -- --sql" from your JSON lists. Run db/schema.sql first.`,
  `-- Replaces the lists of user ${quote(username)}.`,
  `SET NAMES utf8mb4;`,
  `START TRANSACTION;`,
  `INSERT IGNORE INTO app_user (username) VALUES (${quote(username)});`,
  `SET @user = (SELECT id FROM app_user WHERE username = ${quote(username)});`,
  `DELETE FROM characters WHERE user_id = @user; -- and their character_components\n` +
    `DELETE FROM components WHERE user_id = @user;\n` +
    `DELETE FROM words WHERE user_id = @user;`,
  listSql(CHARACTERS_TABLE, characters),
  componentsSql(characters),
  listSql(WORDS_TABLE, words),
  `COMMIT;`,
  ``,
]
  .filter((part, i, all) => part || i === all.length - 1)
  .join('\n\n');

if (sqlOnly) {
  const file = join(ROOT, 'db', 'seed.sql');
  writeFileSync(file, seed);
  console.log(`Wrote ${file}: ${characters.length} characters, ${words.length} words.`);
  process.exit(0);
}

const url = process.env['DATABASE_URL'];
if (!url) {
  console.error('Set DATABASE_URL (or use --sql to only write db/seed.sql).');
  process.exit(1);
}
const db = await mysql.createConnection({ uri: url, multipleStatements: true, charset: 'utf8mb4' });
try {
  await db.query(readFileSync(join(ROOT, 'db', 'schema.sql'), 'utf8'));
  const userId = await userIdOf(db, username);
  const [[{ n }]] = await db.query<mysql.RowDataPacket[]>(
    `SELECT (SELECT COUNT(*) FROM characters WHERE user_id = ?)
          + (SELECT COUNT(*) FROM words WHERE user_id = ?)
          + (SELECT COUNT(*) FROM components WHERE user_id = ?) AS n`,
    [userId, userId, userId],
  );
  if (Number(n) > 0 && !replace) {
    console.error(`User "${username}" already has ${n} rows. Use --replace to overwrite them.`);
    process.exitCode = 1;
  } else {
    await db.query(seed);
    console.log(`Imported ${characters.length} characters and ${words.length} words for "${username}".`);
  }
} finally {
  await db.end();
}
